### ISSUE TITLE
TypeError: Cannot call method 'filter' of undefined

### ISSUE THREAD

**Issue by pborreli** [IonicaBizau/repository-downloader#3] opened 2015-02-15 18:33 UTC
Here the result of the start command:

```
➜  repository-downloader (master) ✔ ./start
info  Getting the organizations you belong to.
info  Getting all your repositories.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
info  Getting the repositories where pborreli created pull requests.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
   >  Page: 10
   >  Page: 11

TypeError: Cannot call method 'filter' of undefined
    at /Users/pborreli/Contrib/repository-downloader/github.js:84:50
    at Request._callback (/Users/pborreli/Contrib/repository-downloader/github.js:43:9)
    at Request.self.callback (/Users/pborreli/Contrib/repository-downloader/node_modules/request/request.js:344:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/pborreli/Contrib/repository-downloader/node_modules/request/request.js:1239:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/pborreli/Contrib/repository-downloader/node_modules/request/request.js:1187:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:442:13)
info  Getting the organizations you belong to.
error SyntaxError: Unexpected end of input
>> */
./import.sh: line 4: cd: */: No such file or directory
>> */
./import.sh: line 7: cd: */: No such file or directory
./import.sh: line 9: cd: */: No such file or directory
>> */
error This is not a git project.

**Comment by IonicaBizau** [comment] 2015-02-15 18:36
Can you log [`res` value here](https://github.com/IonicaBizau/repository-downloader/blob/2a7ef5f78a3aa9e02aaf4f6f1365fea825073589/github.js#L82)?

I'm guessing there is an API limit error, but I'd be curious what's going on there. Thanks!

**Comment by pborreli** [comment] 2015-02-15 18:57
when it crashes res is an [object Object] and res.items is undefined

**Comment by pborreli** [comment] 2015-02-15 18:59
{ message: 'Only the first 1000 search results are available',
  documentation_url: 'https://developer.github.com/v3/search/' }

**Comment by IonicaBizau** [comment] 2015-02-15 19:10
Oh, thanks. I have just committed a fix in the `check-pr-items` branch.

Can you please check if the issue is fixed?

**Comment by pborreli** [comment] 2015-02-15 19:19
now I have:

```
info  Getting the repositories where pborreli created pull requests.
   >  Page: 1
   >  Page: 2
   >  Page: 3
   >  Page: 4
   >  Page: 5
   >  Page: 6
   >  Page: 7
   >  Page: 8
   >  Page: 9
   >  Page: 10
   >  Page: 11
warn  Only the first 1000 search results are available

**Comment by IonicaBizau** [comment] 2015-02-15 19:20
That's fine I guess, like the error says: *only the first 1000 search results are available*.

But I hope that it doesn't stop there, right?

**Comment by pborreli** [comment] 2015-02-15 19:21
no it doesn't stop I opened #4 for the rest of the process :smile:

**Comment by IonicaBizau** [comment] 2015-02-15 19:23
This will be autoclosed via #5.

**Closed** 2015-02-23 06:03 UTC
Labels: bug
